import {GreenApple, BigPotatoes, ChineseCabbage, Corn, Eggplant, FreshCauliflower, FreshIndianMalta, GreenCapsicum, GreenChili, GreenLettuce} from '../../../../assets/Product/Popular/index.js'

const ProductItems =[
    {
        productID :'cardP1',
        cardTitle : 'Green Apple',
        discountPrice : `$20.99`,
        Price : 14.99,
        offer : true,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : GreenApple,
        btnLabel : 'Sale 50%',
        viewRate : 5, 
    },
    {
        productID :'cardP2',
        cardTitle : 'Fresh Indian Malta',
        discountPrice : ``,
        Price : 12.99,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : FreshIndianMalta,
        btnLabel : false,
        viewRate : 4, 
    },
    {
        productID :'cardP3',
        cardTitle : 'Chinese cabbage',
        discountPrice : ``,
        Price : 12.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : ChineseCabbage,
        btnLabel : false,
        viewRate : 4, 
    },
    {
        productID :'cardP4',
        cardTitle : 'Green Lettuce',
        discountPrice : ``,
        Price : 9.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : GreenLettuce,
        btnLabel : false,
        viewRate : 5, 
    },
    {
        productID :'cardP5',
        cardTitle : 'Eggplant',
        discountPrice : ``,
        Price : 34.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : Eggplant,
        btnLabel : false,
        viewRate : 5, 
    },
    {
        productID :'cardP6',
        cardTitle : 'Big Potatoes',
        discountPrice : ``,
        Price : 20.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : BigPotatoes,
        btnLabel : false,
        viewRate : 4, 
    },
    {
        productID :'cardP7',
        cardTitle : 'Corn',
        discountPrice : ``,
        Price : 12.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : Corn,
        btnLabel : false,
        viewRate : 4, 
    },
    {
        productID :'cardP8',
        cardTitle : 'Fresh Cauliflower',
        discountPrice : ``,
        Price : 12.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : FreshCauliflower,
        btnLabel : false,
        viewRate : 4, 
    },
    {
        productID :'cardP9',
        cardTitle : 'Green Capsicum',
        discountPrice : `$20.99`,
        Price : 9.99,
        offer : true,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : GreenCapsicum,
        btnLabel : 'Sale 50%',
        viewRate : 5, 
    },
    {
        productID :'cardP10',
        cardTitle : 'Green Chili',
        discountPrice : ``,
        Price : 34.00,
        offer : false,
        cardSourceAlt : 'The Product information', 
        cardSourceURL : GreenChili,
        btnLabel : false,
        viewRate : 5, 
    },
]
export default ProductItems