import {iceCreamItemSource1, iceCreamItemSource10,iceCreamItemSource11,iceCreamItemSource12,
        iceCreamItemSource2, iceCreamItemSource3, iceCreamItemSource4, iceCreamItemSource5, 
        iceCreamItemSource6, iceCreamItemSource7, iceCreamItemSource8, iceCreamItemSource9
        } from '../../../../assets/Shop/icecream/index.js'

const IceCreamsDB = [
    {
        productID :'iceID1',
        cardTitle : 'Chocolate Chip',
        discountPrice : ``,
        Price : 14.99,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource1,
        btnLabel : ``,
        viewRate : 4, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID2',
        cardTitle : 'Classic Pistachio Gelato',
        discountPrice : ``,
        Price : 6.29,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource2,
        btnLabel : ``,
        viewRate : 4, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID3',
        cardTitle : 'Almond Joy Sundae',
        discountPrice : ``,
        Price : 6.49,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource3,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID4',
        cardTitle : 'Strawberry Balsamic Gelato',
        discountPrice : ``,
        Price : 6.49,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource4,
        btnLabel : ``,
        viewRate : 4, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID5',
        cardTitle : 'Berry Sorbet',
        discountPrice : ``,
        Price : 4.89,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource5,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID6',
        cardTitle : 'Chocolate Hazelnut Gelato',
        discountPrice : ``,
        Price : 6.39,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource6,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID7',
        cardTitle : 'Chocolate Fudge',
        discountPrice : ``,
        Price : 5.99,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource7,
        btnLabel : ``,
        viewRate : 4, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID8',
        cardTitle : 'Classic Pistachio Gelato',
        discountPrice : ``,
        Price : 6.29,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource8,
        btnLabel : ``,
        viewRate : 3, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID9',
        cardTitle : 'Dairy Free Classic',
        discountPrice : ``,
        Price : 6.49,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource9,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID10',
        cardTitle : 'Strawberry Balsamic Gelato',
        discountPrice : ``,
        Price : 5.99,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource10,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID11',
        cardTitle : 'Dairy Free mond',
        discountPrice : ``,
        Price : 4.89,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource11,
        btnLabel : ``,
        viewRate : 3, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
    {
        productID :'iceID12',
        cardTitle : 'Chocolate Hazelnut Gelato',
        discountPrice : ``,
        Price : 6.79,
        offer : false,
        cardSourceAlt : 'The Product Ice cream', 
        cardSourceURL : iceCreamItemSource1,
        btnLabel : ``,
        viewRate : 5, 
        isVisible: true,
        isFruit: true,
        stock: `In Stock`
    },
]

export default IceCreamsDB