export { default as Fruit } from './Fruit';
export { default as Vegetables } from './Vegetables';
export { default as Fish } from './Fish';
export { default as Meat } from './Meat';
export { default as Drink } from './Drink';
export { default as IceCream } from './IceCream';
export { default as Bread } from './Bread';
export { default as Butter } from './Butter';
export { default as Cooking } from './Cooking';
