export { default as Home } from './Home';
export { default as Shop } from './Shop';
export { default as Blog } from './Blog';
export { default as Pages } from './Pages';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Product } from './Product';
export {default as SingleBlogs} from './SingleBlogs';
export {default as SignIn} from './Auth/SignIn';
export {default as SignUp} from './Auth/SignUp';