export {default as Cart } from './Cart'
export {default as OrderHistory } from './OrderHistory'
export {default as MyAccount } from './MyAccount'
export {default as Wishlist } from './Wishlist'
export {default as Setting } from './Setting'
export {default as OrderDetails } from './OrderDetails'